baseURL = 'https://blog.harify.com/'
languageCode = 'en-us'
title = 'Harify Palm'
theme = 'mini-custom'
enableRobotsTXT = true

[params]
description = "A blog on how to do Software Engineering the alien way!"
